[package]
name = "typebit_native"
version = "0.1.1"
edition = "2021"
license-file = "../LICENSE"
description = "JNI bridge embedding the TypeBit BitTorrent engine for Android and JVM desktop."
readme = "README.md"

[lib]
name = "typebit_native"
crate-type = ["cdylib"]

[dependencies]
typebit = { version = "0.1.9", features = ["std"] }
jni = { version = "0.22.4" }
getrandom = "0.4"
nextjson = { version = "0.1", default-features = false }
courierust = { version = "1.0.9", default-features = false, features = ["std"] }
recurse-x = { version = "0.2.3", default-features = false, features = [
    "std",
    "dot",
    "doh",
    "dnssec",
] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
] }

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
panic = "unwind"
