[package]
name = "typebit_native"
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
license-file = "../LICENSE"
description = "JNI bridge embedding the TypeBit BitTorrent engine for Android and JVM desktop."
readme = "README.md"

[lib]
name = "typebit_native"
crate-type = ["cdylib"]

[dependencies]
typebit = { version = "0.1.1", features = ["std"] }
jni = { version = "0.22.4"}
getrandom = "0.4"
nextjson = { version = "0.1", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
panic = "unwind"
