# Builds the Android native bridge (.so for each ABI) and copies them into
# composeApp/src/androidMain/jniLibs so the APK bundles them.
#
# Usage:
#   $env:ANDROID_NDK_HOME = "C:\...\Sdk\ndk\26.2.11394342"
#   powershell -ExecutionPolicy Bypass -File scripts/build-android.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$native = Join-Path $root "native"

$ndk = $env:ANDROID_NDK_HOME
if (-not $ndk) {
    $default = Join-Path $env:LOCALAPPDATA "Android\Sdk\ndk\26.2.11394342"
    if (Test-Path $default) { $ndk = $default }
}
if (-not $ndk -or -not (Test-Path $ndk)) {
    throw "ANDROID_NDK_HOME not set and no default NDK found. Set ANDROID_NDK_HOME."
}

# Regenerate .cargo/config.toml with the concrete NDK path (Cargo does not
# expand ${VAR} in linker/ar entries).
$config = @"
# Auto-generated by scripts/build-android.ps1 — do not edit by hand.
[target.aarch64-linux-android]
linker = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd"
ar = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

[target.armv7-linux-androideabi]
linker = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi24-clang.cmd"
ar = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

[target.x86_64-linux-android]
linker = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android24-clang.cmd"
ar = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

[target.i686-linux-android]
linker = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android24-clang.cmd"
ar = "$ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar"

[target.x86_64-pc-windows-msvc]
linker = "link.exe"
"@
$config | Set-Content -Path (Join-Path $native ".cargo\config.toml") -Encoding UTF8

$targets = @(
    @{ Triple = "aarch64-linux-android"; ABI = "arm64-v8a" },
    @{ Triple = "armv7-linux-androideabi"; ABI = "armeabi-v7a" },
    @{ Triple = "x86_64-linux-android"; ABI = "x86_64" },
    @{ Triple = "i686-linux-android"; ABI = "x86" }
)

Push-Location $native
try {
    foreach ($t in $targets) {
        Write-Host "[typebit] building $($t.Triple)..." -ForegroundColor Cyan
        cargo build --target $t.Triple --release
        if ($LASTEXITCODE -ne 0) { throw "cargo build failed for $($t.Triple)" }
        $so = Join-Path $native "target\$($t.Triple)\release\libtypebit_native.so"
        $destDir = Join-Path $root "composeApp\src\androidMain\jniLibs\$($t.ABI)"
        New-Item -ItemType Directory -Force -Path $destDir | Out-Null
        Copy-Item -Force $so (Join-Path $destDir "libtypebit_native.so")
        Write-Host "[typebit] deployed $($t.ABI)/libtypebit_native.so" -ForegroundColor Green
    }
} finally {
    Pop-Location
}
